# Generated by Django 5.1.1 on 2024-10-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery_photos/')),
                ('description', models.TextField(blank=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
