# Generated by Django 5.1.1 on 2024-10-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='avatar',
        ),
        migrations.AddField(
            model_name='feedback',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к аватарке'),
        ),
    ]
