# Generated by Django 5.1.1 on 2024-10-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_alter_gallery_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryImages',
        ),
    ]
